Disable sanity check

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -25,14 +25,14 @@ jobs:
       - name: List files
         run: ls -R
 
-      - name: Check for package-lock.json
-        run: |
-          if [ -f ngafid-frontend/package-lock.json ]; then
-            echo "✅ Found package-lock.json"
-          else
-            echo "❌ Failed to find package-lock.json"
-            exit 1
-          fi
+      # - name: Check for package-lock.json
+      #   run: |
+      #     if [ -f ngafid-frontend/package-lock.json ]; then
+      #       echo "✅ Found package-lock.json"
+      #     else
+      #       echo "❌ Failed to find package-lock.json"
+      #       exit 1
+      #     fi
 
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v4
